version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
    - 4000:4000
    environment:
      - MIX_BUILD_PATH=/volumes/_build/dev
      - MIX_DEPS_PATH=/volumes/deps
      # - METRICS_TYPE=prometheus
      # - METRICS_PROMETHEUS_PORT=9568
    volumes:
      - type: volume
        source: build_vol
        target: /volumes/_build
      - type: volume
        source: deps_vol
        target: /volumes/deps
      - type: bind
        source: ./
        target: /app

  # statsd:
  #   image: statsd/statsd:v0.10.2
  #   ports:
  #   - 8125:8125/udp
  #   - 8126:8126
  #   volumes:
  #     - "./statsd_config.js:/usr/src/app/config.js"

  # otel:
  #   image: otel/opentelemetry-collector-contrib:0.88.0
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
  #   ports:
  #     - 1888:1888 # pprof extension
  #     - 8888:8888 # Prometheus metrics exposed by the collector
  #     - 8889:8889 # Prometheus exporter metrics
  #     - 13133:13133 # health_check extension
  #     - 4317:4317 # OTLP gRPC receiver
  #     - 4318:4318 # OTLP http receiver
  #     - 55679:55679 # zpages extension
  #     # - 8127:8127/udp # Statsd receiver

volumes:
  build_vol:
  deps_vol: