receivers:
  statsd:
    endpoint: "0.0.0.0:8127"
    aggregation_interval: 5s

  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

  # prometheus:
  #   config:
  #     scrape_configs:
  #     - job_name: 'otelcol'
  #       scrape_interval: 10s
  #       static_configs:
  #       - targets: ['0.0.0.0:8888']
  #       metric_relabel_configs:
  #         - source_labels: [ __name__ ]
  #           regex: '.*grpc_io.*'
  #           action: drop

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  debug:
    verbosity: detailed

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [statsd]
      processors: []
      exporters: [debug]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [debug, otlp/jaeger]
